In [1]:
# Please change the following to your own PAPER api key and secret
# or set them as environment variables (ALPACA_API_KEY, ALPACA_SECRET_KEY).
# You can get them from https://alpaca.markets/

api_key = None
secret_key = None

#### We use paper environment for this example ####
paper = True # Please do not modify this. This example is for paper trading only.
####

# Below are the variables for development this documents
# Please do not change these variables
trade_api_url = None
trade_api_wss = None
data_api_url = None
stream_data_wss = None

In [2]:
import os
from dotenv import load_dotenv
load_dotenv()

if api_key is None:
    api_key = os.environ.get('ALPACA_API_KEY')

if secret_key is None:
    secret_key = os.environ.get('ALPACA_SECRET_KEY')

In [7]:
# install alpaca-py if it is not available
try:
    import alpaca
except ImportError:
    !python3 -m pip install alpaca-py
    import alpaca

In [41]:
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

from alpaca.trading.client import TradingClient
from alpaca.data.timeframe import TimeFrame, TimeFrameUnit
from alpaca.data.historical.corporate_actions import CorporateActionsClient
from alpaca.data.historical.stock import StockHistoricalDataClient
from alpaca.trading.stream import TradingStream
from alpaca.data.live.stock import StockDataStream

from alpaca.data.requests import (
    CorporateActionsRequest,
    StockBarsRequest,
    StockQuotesRequest,
    StockTradesRequest,
)
from alpaca.trading.requests import (
    ClosePositionRequest,
    GetAssetsRequest,
    GetOrdersRequest,
    LimitOrderRequest,
    MarketOrderRequest,
    StopLimitOrderRequest,
    StopLossRequest,
    StopOrderRequest,
    TakeProfitRequest,
    TrailingStopOrderRequest,
)
from alpaca.trading.enums import (
    AssetExchange,
    AssetStatus,
    OrderClass,
    OrderSide,
    OrderType,
    QueryOrderStatus,
    TimeInForce,
)
from alpaca.common.enums import (
    Sort,
)

In [9]:
# to run async code in jupyter notebook
import nest_asyncio
nest_asyncio.apply()

In [10]:
# check version of alpaca-py
alpaca.__version__

'0.43.2'

In [11]:
# setup stock historical data client
stock_historical_data_client = StockHistoricalDataClient(api_key, secret_key, url_override = data_api_url)

In [51]:
import polars as pl
import altair as alt

symbol = "SPY"

In [60]:
# get historical bars by symbol
# ref. https://docs.alpaca.markets/reference/stockbars-1
now = datetime.now(ZoneInfo("America/New_York"))
req = StockBarsRequest(
    symbol_or_symbols = [symbol],
    timeframe=TimeFrame(amount = 1, unit = TimeFrameUnit.Day), # specify timeframe
    start = now - timedelta(days = 600),                          # specify start datetime, default=the beginning of the current day.
    # end_date=None,                                        # specify end datetime, default=now
    limit = 600,                                               # specify limit
    sort = Sort.ASC,
)
hist_data = stock_historical_data_client.get_stock_bars(req)
hist_data

{   'data': {   'SPY': [   {   'close': 542.74,
                               'high': 546.95,
                               'low': 542.62,
                               'open': 544.33,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 6, 24, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 392113.0,
                               'volume': 45528654.0,
                               'vwap': 544.440534},
                           {   'close': 544.83,
                               'high': 545.2,
                               'low': 542.44,
                               'open': 543.99,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 6, 25, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 314940.0,
                               'volume': 38273346.0,
                               'vwap': 544.104149},
                           {   'close': 545.51,
                               'high': 546.24,
                               'low': 543.03,
                               'open': 543.69,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 6, 26, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 336264.0,
                               'volume': 38550637.0,
                               'vwap': 544.662273},
                           {   'close': 546.37,
                               'high': 546.96,
                               'low': 544.61,
                               'open': 545.37,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 6, 27, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 318146.0,
                               'volume': 35041480.0,
                               'vwap': 545.767008},
                           {   'close': 544.22,
                               'high': 550.28,
                               'low': 542.95,
                               'open': 547.16,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 6, 28, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 490952.0,
                               'volume': 75925045.0,
                               'vwap': 546.132413},
                           {   'close': 545.34,
                               'high': 545.88,
                               'low': 542.52,
                               'open': 545.63,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 1, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 370685.0,
                               'volume': 40297810.0,
                               'vwap': 544.684439},
                           {   'close': 549.01,
                               'high': 549.01,
                               'low': 543.65,
                               'open': 543.7,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 2, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 326760.0,
                               'volume': 40434792.0,
                               'vwap': 546.880645},
                           {   'close': 551.46,
                               'high': 551.83,
                               'low': 548.65,
                               'open': 548.69,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 3, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 253838.0,
                               'volume': 32789911.0,
                               'vwap': 550.337491},
                           {   'close': 554.64,
                               'high': 555.05,
                               'low': 551.12,
                               'open': 551.77,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 5, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 339620.0,
                               'volume': 41488389.0,
                               'vwap': 553.632822},
                           {   'close': 555.28,
                               'high': 556.2501,
                               'low': 554.19,
                               'open': 555.44,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 8, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 315486.0,
                               'volume': 36110451.0,
                               'vwap': 555.150626},
                           {   'close': 555.82,
                               'high': 557.18,
                               'low': 555.52,
                               'open': 556.26,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 9, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 298712.0,
                               'volume': 27314125.0,
                               'vwap': 556.17382},
                           {   'close': 561.32,
                               'high': 561.67,
                               'low': 556.77,
                               'open': 557.07,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 10, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 339735.0,
                               'volume': 38701220.0,
                               'vwap': 559.350535},
                           {   'close': 556.48,
                               'high': 562.33,
                               'low': 555.83,
                               'open': 561.44,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 11, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 458805.0,
                               'volume': 53054184.0,
                               'vwap': 557.90259},
                           {   'close': 559.99,
                               'high': 563.67,
                               'low': 557.15,
                               'open': 557.63,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 12, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 418470.0,
                               'volume': 53084405.0,
                               'vwap': 560.737146},
                           {   'close': 561.53,
                               'high': 564.8371,
                               'low': 559.63,
                               'open': 562.03,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 15, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 398072.0,
                               'volume': 40584293.0,
                               'vwap': 562.110674},
                           {   'close': 564.86,
                               'high': 565.16,
                               'low': 562.1,
                               'open': 562.865,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 16, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 354166.0,
                               'volume': 36475260.0,
                               'vwap': 563.682953},
                           {   'close': 556.94,
                               'high': 560.51,
                               'low': 556.61,
                               'open': 558.8,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 17, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 472516.0,
                               'volume': 57118956.0,
                               'vwap': 558.047099},
                           {   'close': 552.66,
                               'high': 559.52,
                               'low': 550.43,
                               'open': 558.51,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 18, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 510019.0,
                               'volume': 56270392.0,
                               'vwap': 554.093499},
                           {   'close': 548.99,
                               'high': 554.08,
                               'low': 547.91,
                               'open': 552.42,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 19, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 446111.0,
                               'volume': 65509081.0,
                               'vwap': 549.923605},
                           {   'close': 554.65,
                               'high': 555.27,
                               'low': 551.02,
                               'open': 553.0,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 22, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 419641.0,
                               'volume': 43346720.0,
                               'vwap': 553.63256},
                           {   'close': 553.78,
                               'high': 556.735,
                               'low': 553.275,
                               'open': 554.54,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 23, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 308680.0,
                               'volume': 34439561.0,
                               'vwap': 554.947013},
                           {   'close': 541.23,
                               'high': 549.17,
                               'low': 540.29,
                               'open': 548.86,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 24, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 537919.0,
                               'volume': 74515266.0,
                               'vwap': 543.775404},
                           {   'close': 538.41,
                               'high': 547.455,
                               'low': 537.45,
                               'open': 541.35,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 25, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 555720.0,
                               'volume': 61158288.0,
                               'vwap': 541.737207},
                           {   'close': 544.44,
                               'high': 547.19,
                               'low': 541.49,
                               'open': 542.28,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 26, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 458201.0,
                               'volume': 53763788.0,
                               'vwap': 544.081331},
                           {   'close': 544.76,
                               'high': 547.05,
                               'low': 542.72,
                               'open': 546.02,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 29, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 364441.0,
                               'volume': 39515824.0,
                               'vwap': 545.305528},
                           {   'close': 542.0,
                               'high': 547.34,
                               'low': 538.515,
                               'open': 546.26,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 30, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 428534.0,
                               'volume': 46853632.0,
                               'vwap': 542.546757},
                           {   'close': 550.81,
                               'high': 553.5,
                               'low': 547.5799,
                               'open': 548.98,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 7, 31, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 499830.0,
                               'volume': 65663388.0,
                               'vwap': 550.610032},
                           {   'close': 543.01,
                               'high': 554.8688,
                               'low': 539.43,
                               'open': 552.57,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 8, 1, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 658124.0,
                               'volume': 76428732.0,
                               'vwap': 544.809871},
                           {   'close': 532.9,
                               'high': 536.99,
                               'low': 528.6,
                               'open': 535.75,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 8, 2, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 746100.0,
                               'volume': 82789070.0,
                               'vwap': 531.726908},
                           {   'close': 517.38,
                               'high': 523.58,
                               'low': 510.27,
                               'open': 511.64,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 8, 5, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 1274896.0,
                               'volume': 146267391.0,
                               'vwap': 517.191195},
                           {   'close': 522.15,
                               'high': 529.75,
                               'low': 517.87,
                               'open': 519.22,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 8, 6, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 731363.0,
                               'volume': 84826312.0,
                               'vwap': 524.399558},
                           {   'close': 518.66,
                               'high': 531.59,
                               'low': 518.0519,
                               'open': 528.47,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 8, 7, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 644157.0,
                               'volume': 70698340.0,
                               'vwap': 524.14742},
                           {   'close': 530.65,
                               'high': 531.29,
                               'low': 521.84,
                               'open': 523.91,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 8, 8, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 570742.0,
                               'volume': 63276589.0,
                               'vwap': 528.220388},
                           {   'close': 532.99,
                               'high': 534.51,
                               'low': 528.56,
                               'open': 529.81,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 8, 9, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 459823.0,
                               'volume': 45619558.0,
                               'vwap': 531.740787},
                           {   'close': 533.27,
                               'high': 535.73,
                               'low': 530.95,
                               'open': 534.21,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 8, 12, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 437515.0,
                               'volume': 42542069.0,
                               'vwap': 533.215795},
                           {   'close': 542.04,
                               'high': 542.28,
                               'low': 536.28,
                               'open': 536.53,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 8, 13, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 422228.0,
                               'volume': 52333073.0,
                               'vwap': 540.0315},
                           {   'close': 543.75,
                               'high': 544.96,
                               'low': 540.12,
                               'open': 542.85,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 8, 14, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 389697.0,
                               'volume': 42446929.0,
                               'vwap': 543.081967},
                           {   'close': 553.07,
                               'high': 553.36,
                               'low': 548.88,
                               'open': 549.5,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 8, 15, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 480232.0,
                               'volume': 60846812.0,
                               'vwap': 551.705097},
                           {   'close': 554.31,
                               'high': 555.02,
                               'low': 551.26,
                               'open': 551.42,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 8, 16, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 328824.0,
                               'volume': 44430728.0,
                               'vwap': 553.519424},
                           {   'close': 559.61,
                               'high': 559.61,
                               'low': 553.86,
                               'open': 554.73,
                               'symbol': 'SPY',
                               'timestamp': datetime.datetime(2024, 8, 19, 4, 0, tzinfo=TzInfo(UTC)),
                               'trade_count': 365312.0,
                               'volume': 39121793.0,
                               'vwap': 557.241465},
                           {   'close': 558.7,

In [61]:
hist_data_polars = pl.DataFrame(hist_data.data[symbol])
hist_data_polars

shape: (410, 9)
┌────────┬────────────────┬────────┬────────┬───┬────────┬──────────────┬─────────────┬────────────┐
│ symbol ┆ timestamp      ┆ open   ┆ high   ┆ … ┆ close  ┆ volume       ┆ trade_count ┆ vwap       │
│ ---    ┆ ---            ┆ ---    ┆ ---    ┆   ┆ ---    ┆ ---          ┆ ---         ┆ ---        │
│ str    ┆ datetime[μs]   ┆ f64    ┆ f64    ┆   ┆ f64    ┆ f64          ┆ f64         ┆ f64        │
╞════════╪════════════════╪════════╪════════╪═══╪════════╪══════════════╪═════════════╪════════════╡
│ SPY    ┆ 2024-06-24     ┆ 544.33 ┆ 546.95 ┆ … ┆ 542.74 ┆ 4.5528654e7  ┆ 392113.0    ┆ 544.440534 │
│        ┆ 04:00:00       ┆        ┆        ┆   ┆        ┆              ┆             ┆            │
│ SPY    ┆ 2024-06-25     ┆ 543.99 ┆ 545.2  ┆ … ┆ 544.83 ┆ 3.8273346e7  ┆ 314940.0    ┆ 544.104149 │
│        ┆ 04:00:00       ┆        ┆        ┆   ┆        ┆              ┆             ┆            │
│ SPY    ┆ 2024-06-26     ┆ 543.69 ┆ 546.24 ┆ … ┆ 545.51 ┆ 3.8550637e7  ┆ 336264.0    ┆ 544.662273 │
│        ┆ 04:00:00       ┆        ┆        ┆   ┆        ┆              ┆             ┆            │
│ SPY    ┆ 2024-06-27     ┆ 545.37 ┆ 546.96 ┆ … ┆ 546.37 ┆ 3.504148e7   ┆ 318146.0    ┆ 545.767008 │
│        ┆ 04:00:00       ┆        ┆        ┆   ┆        ┆              ┆             ┆            │
│ SPY    ┆ 2024-06-28     ┆ 547.16 ┆ 550.28 ┆ … ┆ 544.22 ┆ 7.5925045e7  ┆ 490952.0    ┆ 546.132413 │
│        ┆ 04:00:00       ┆        ┆        ┆   ┆        ┆              ┆             ┆            │
│ …      ┆ …              ┆ …      ┆ …      ┆ … ┆ …      ┆ …            ┆ …           ┆ …          │
│ SPY    ┆ 2026-02-04     ┆ 690.35 ┆ 691.45 ┆ … ┆ 686.19 ┆ 1.052046e8   ┆ 1.712102e6  ┆ 686.716173 │
│        ┆ 05:00:00       ┆        ┆        ┆   ┆        ┆              ┆             ┆            │
│ SPY    ┆ 2026-02-05     ┆ 680.94 ┆ 683.69 ┆ … ┆ 677.62 ┆ 1.13610812e8 ┆ 1.703564e6  ┆ 679.01231  │
│        ┆ 05:00:00       ┆        ┆        ┆   ┆        ┆              ┆             ┆            │
│ SPY    ┆ 2026-02-06     ┆ 681.46 ┆ 692.31 ┆ … ┆ 690.62 ┆ 8.9127566e7  ┆ 1.394903e6  ┆ 687.550511 │
│        ┆ 05:00:00       ┆        ┆        ┆   ┆        ┆              ┆             ┆            │
│ SPY    ┆ 2026-02-09     ┆ 689.42 ┆ 695.87 ┆ … ┆ 693.95 ┆ 7.3885192e7  ┆ 1.089458e6  ┆ 693.630023 │
│        ┆ 05:00:00       ┆        ┆        ┆   ┆        ┆              ┆             ┆            │
│ SPY    ┆ 2026-02-10     ┆ 694.95 ┆ 696.54 ┆ … ┆ 692.12 ┆ 6.5184127e7  ┆ 997738.0    ┆ 694.069154 │
│        ┆ 05:00:00       ┆        ┆        ┆   ┆        ┆              ┆             ┆            │
└────────┴────────────────┴────────┴────────┴───┴────────┴──────────────┴─────────────┴────────────┘

In [62]:
# Transform data
data = hist_data_polars.with_columns(# exponential moving average
                        pl.col("close").ewm_mean(span=5, adjust=False).alias('ema_5'),
                        pl.col("close").shift(1).ewm_mean(span=5, adjust=False).alias('prior_ema_5'),
                        pl.col("close").ewm_mean(span=20, adjust=False).alias('ema_20'),
                        pl.col("close").shift(1).ewm_mean(span=20, adjust=False).alias('prior_ema_20'),
                        pl.col("close").ewm_mean(span=50, adjust=True, ignore_nulls=True).alias('ema_50'),
                        pl.col("close").shift(1).ewm_mean(span=50, adjust=True, ignore_nulls=True).alias('prior_ema_50'),
                        pl.col("close").ewm_mean(span=200, adjust=True, ignore_nulls=True).alias('ema_200'),
                        pl.col("close").shift(1).ewm_mean(span=200, adjust=True, ignore_nulls=True).alias('prior_ema_200'),
                        # Simple moving avaerage
                        pl.col("close").rolling_mean(10).alias("close_MA10"),
                        pl.col("close").rolling_mean(20).alias("close_MA20"))
data = data.with_columns(pl.when((pl.col("ema_5") > pl.col("ema_20")) & (pl.col("prior_ema_5") <= pl.col("prior_ema_20")))
                            .then(pl.col("close")*0.98).alias("sig_bull_5_20"),
                        pl.when((pl.col("ema_5") < pl.col("ema_20")) & (pl.col("prior_ema_5") >= pl.col("prior_ema_20")))
                            .then(pl.col("close")*0.98).alias("sig_bear_5_20"),
                        pl.when((pl.col("ema_20") > pl.col("ema_50")) & (pl.col("prior_ema_20") <= pl.col("prior_ema_50")))
                            .then(pl.col("close")*0.98).alias("sig_bull_20_50"),
                        pl.when((pl.col("ema_20") < pl.col("ema_50")) & (pl.col("prior_ema_20") >= pl.col("prior_ema_50")))
                            .then(pl.col("close")*0.98).alias("sig_bear_20_50"),
                        pl.when((pl.col("ema_50") > pl.col("ema_200")) & (pl.col("prior_ema_50") <= pl.col("prior_ema_200")))
                            .then(pl.col("close")*0.98).alias("sig_bull_50_200"),
                        pl.when((pl.col("ema_50") < pl.col("ema_200")) & (pl.col("prior_ema_50") >= pl.col("prior_ema_200")))
                            .then(pl.col("close")*0.98).alias("sig_bear_50_200"),)
data

shape: (410, 25)
┌────────┬─────────────┬────────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ symbol ┆ timestamp   ┆ open   ┆ high   ┆ … ┆ sig_bull_20 ┆ sig_bear_20 ┆ sig_bull_5 ┆ sig_bear_5 │
│ ---    ┆ ---         ┆ ---    ┆ ---    ┆   ┆ _50         ┆ _50         ┆ 0_200      ┆ 0_200      │
│ str    ┆ datetime[μs ┆ f64    ┆ f64    ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│        ┆ ]           ┆        ┆        ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞════════╪═════════════╪════════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ SPY    ┆ 2024-06-24  ┆ 544.33 ┆ 546.95 ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆ 04:00:00    ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ SPY    ┆ 2024-06-25  ┆ 543.99 ┆ 545.2  ┆ … ┆ null        ┆ 533.9334    ┆ 533.9334   ┆ null       │
│        ┆ 04:00:00    ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ SPY    ┆ 2024-06-26  ┆ 543.69 ┆ 546.24 ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆ 04:00:00    ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ SPY    ┆ 2024-06-27  ┆ 545.37 ┆ 546.96 ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆ 04:00:00    ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ SPY    ┆ 2024-06-28  ┆ 547.16 ┆ 550.28 ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆ 04:00:00    ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ …      ┆ …           ┆ …      ┆ …      ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ SPY    ┆ 2026-02-04  ┆ 690.35 ┆ 691.45 ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆ 05:00:00    ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ SPY    ┆ 2026-02-05  ┆ 680.94 ┆ 683.69 ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆ 05:00:00    ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ SPY    ┆ 2026-02-06  ┆ 681.46 ┆ 692.31 ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆ 05:00:00    ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ SPY    ┆ 2026-02-09  ┆ 689.42 ┆ 695.87 ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆ 05:00:00    ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
│ SPY    ┆ 2026-02-10  ┆ 694.95 ┆ 696.54 ┆ … ┆ null        ┆ null        ┆ null       ┆ null       │
│        ┆ 05:00:00    ┆        ┆        ┆   ┆             ┆             ┆            ┆            │
└────────┴─────────────┴────────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [63]:
# Plot data using a long dataframe format for price data

# First convert from wide to long using unpivot
columns = ['timestamp', 'close', 'ema_50', 'ema_200']
line_columns = data.select(columns)
long_data = line_columns.unpivot(index='timestamp', on=['close', 'ema_50', 'ema_200'], variable_name='type', value_name='value')

line_chart = (
    alt.Chart(long_data)
    .mark_line(strokeWidth=1)
    .encode(x=alt.X("timestamp:T",
                    title='',
                    axis=alt.Axis(labelAngle=-45, tickColor="#09080B", domainColor="#09080B", grid=False, labelFontSize=10, titleFontSize=12)),
            y=alt.Y("value:Q",
                    title='Close',
                    scale=alt.Scale(zero=False),
                    axis=alt.Axis(format='$.2f', tickColor="#09080B", domainColor="#09080B", gridColor="#9DCDF8", grid=True, labelFontSize=10, titleFontSize=12)
                    ),
            color="type:N",
            tooltip=['timestamp:T', 'value:Q'])
    ).properties(title={'text': 'Stock Price Analysis',
                        'subtitle': ['50 and 200-day exponential moving average overlay'],
                        'fontSize': 16
                },
                width=500,
                height=300,
    )

xrule = (
        alt.Chart()
        .mark_rule(color="#00FFFF", strokeWidth=2)
        .encode(x=alt.datum(alt.DateTime(year=2024, month="November")))
)

yrule = (
    alt.Chart().mark_rule(color="#1010AA", strokeDash=[12, 6], size=2).encode(y=alt.datum(550))
)

bull_sig = (
    alt.Chart(data)
    .mark_point(shape='triangle-up',color="#0F9A0F",size=30, strokeWidth=3)
    .encode(x='timestamp:T',
            y='sig_bull_50_200'))

bear_sig = (
    alt.Chart(data)
    .mark_point(shape='triangle-down',color='#FF0000',size=30, strokeWidth=3)
    .encode(x='timestamp:T',
            y='sig_bear_50_200'))

#Layer the above five together
line_chart = (line_chart + xrule + yrule + bull_sig + bear_sig).interactive()

bar_chart = alt.Chart(data).mark_bar(color="#4286B4",opacity=1.0
    ).encode(x=alt.X("timestamp:T",
                title='Date',
                axis=alt.Axis(labelAngle=-45, tickColor="#09080B", domainColor="#09080B", grid=False, labelFontSize=10, titleFontSize=12)
                ),
            y=alt.Y('volume:Q',
                    title='Volume',
                    axis=alt.Axis(tickColor="#09080B", domainColor="#09080B", gridColor="#9DCDF8", grid=True, labelFontSize=10,titleFontSize=12)
                    ),
            tooltip=['timestamp:T', 'Volume:Q'],
    ).properties(title='Volume',
                width=500,
                height=150,)

# Vertically combine the charts
combined_chart = alt.vconcat(line_chart, bar_chart).resolve_scale(x='shared').configure(background="#CBE1F6")
combined_chart.show()

alt.VConcatChart(...)